services:
  postgres:
    image: postgres:16
    container_name: bda_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_DB: olist
    ports:
      - "5435:5432"
    volumes:
      - postgres16_data:/var/lib/postgresql/data

  doris-fe:
    image: apache/doris:fe-4.0.3-slim
    container_name: doris-fe
    hostname: doris-fe
    environment:
      FE_SERVERS: "fe1:172.28.0.10:9010"
      FE_ID: "1"
    ports:
      - "8030:8030"
      - "9030:9030"
      - "9010:9010"
    volumes:
      - doris_fe_meta:/opt/apache-doris/fe/doris-meta
      - doris_fe_log:/opt/apache-doris/fe/log
    networks:
      dorisnet:
        ipv4_address: 172.28.0.10

  doris-be:
    image: apache/doris:be-4.0.3-slim
    container_name: doris-be
    hostname: doris-be
    depends_on:
      - doris-fe
    environment:
      FE_SERVERS: "fe1:172.28.0.10:9010"
      BE_ADDR: "172.28.0.11:9050"
    ports:
      - "8040:8040"
      - "9050:9050"
      - "9060:9060"
    volumes:
      - doris_be_storage:/opt/apache-doris/be/storage
      - doris_be_log:/opt/apache-doris/be/log
    networks:
      dorisnet:
        ipv4_address: 172.28.0.11

volumes:
  postgres16_data:
  doris_fe_meta:
  doris_fe_log:
  doris_be_storage:
  doris_be_log:

networks:
  dorisnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16